export type ActionCodeEntry = {
  route: string;
  step: string;
  flags?: string[];
  status?: "active" | "legacy" | "system";
};

export type ActionCodeRegistryShape = {
  version: string;
  actions: Record<string, ActionCodeEntry>;
  menus: Record<string, string[]>;
  ui_flags: Record<string, { showPurposeHint?: boolean }>;
};

export const ACTIONCODE_REGISTRY_VERSION =
  (process.env.ACTIONCODE_REGISTRY_VERSION || "").trim() || "dev";

export const ACTIONCODE_REGISTRY: ActionCodeRegistryShape = {
  version: ACTIONCODE_REGISTRY_VERSION,
  actions: {
    // Step 0
    ACTION_STEP0_META_RETURN: { route: "__ROUTE__STEP0_META_RETURN__", step: "step_0" },
    ACTION_STEP0_READY_START: { route: "__ROUTE__STEP0_READY_START__", step: "step_0" },

    // Dream
    ACTION_DREAM_INTRO_EXPLAIN_MORE: { route: "__ROUTE__DREAM_EXPLAIN_MORE__", step: "dream" },
    ACTION_DREAM_INTRO_START_EXERCISE: { route: "__ROUTE__DREAM_START_EXERCISE__", step: "dream" },
    ACTION_DREAM_WHY_GIVE_SUGGESTIONS: { route: "__ROUTE__DREAM_GIVE_SUGGESTIONS__", step: "dream" },
    ACTION_DREAM_WHY_START_EXERCISE: { route: "__ROUTE__DREAM_START_EXERCISE__", step: "dream" },
    ACTION_DREAM_SUGGESTIONS_PICK_ONE: { route: "__ROUTE__DREAM_PICK_ONE__", step: "dream" },
    ACTION_DREAM_SUGGESTIONS_START_EXERCISE: { route: "__ROUTE__DREAM_START_EXERCISE__", step: "dream" },
    ACTION_DREAM_REFINE_CONFIRM: { route: "yes", step: "dream", flags: ["confirm"] },
    ACTION_DREAM_REFINE_START_EXERCISE: { route: "__ROUTE__DREAM_START_EXERCISE__", step: "dream" },
    ACTION_DREAM_ESCAPE_CONTINUE: { route: "__ROUTE__DREAM_CONTINUE__", step: "dream" },
    ACTION_DREAM_ESCAPE_FINISH_LATER: { route: "__ROUTE__DREAM_FINISH_LATER__", step: "dream" },
    ACTION_DREAM_SWITCH_TO_SELF: { route: "__SWITCH_TO_SELF_DREAM__", step: "dream" },

    // DreamExplainer
    ACTION_DREAM_EXPLAINER_CONTINUE: { route: "__ROUTE__DREAM_EXPLAINER_CONTINUE__", step: "dream" },
    ACTION_DREAM_EXPLAINER_FINISH_LATER: { route: "__ROUTE__DREAM_EXPLAINER_FINISH_LATER__", step: "dream" },
    ACTION_DREAM_EXPLAINER_REFINE_CONFIRM: { route: "__ROUTE__DREAM_EXPLAINER_CONTINUE_TO_PURPOSE__", step: "dream" },
    ACTION_DREAM_EXPLAINER_REFINE_ADJUST: { route: "__ROUTE__DREAM_EXPLAINER_REFINE__", step: "dream" },
    ACTION_DREAM_EXPLAINER_NEXT_STEP: { route: "Next step", step: "dream" },
    ACTION_DREAM_EXPLAINER_SUBMIT_SCORES: { route: "ACTION_DREAM_EXPLAINER_SUBMIT_SCORES", step: "dream" },

    // Purpose
    ACTION_PURPOSE_INTRO_EXPLAIN_MORE: { route: "__ROUTE__PURPOSE_EXPLAIN_MORE__", step: "purpose" },
    ACTION_PURPOSE_EXPLAIN_ASK_3_QUESTIONS: { route: "__ROUTE__PURPOSE_ASK_3_QUESTIONS__", step: "purpose" },
    ACTION_PURPOSE_EXPLAIN_GIVE_EXAMPLES: { route: "__ROUTE__PURPOSE_GIVE_EXAMPLES__", step: "purpose" },
    ACTION_PURPOSE_EXAMPLES_ASK_3_QUESTIONS: { route: "__ROUTE__PURPOSE_ASK_3_QUESTIONS__", step: "purpose" },
    ACTION_PURPOSE_EXAMPLES_CHOOSE_FOR_ME: { route: "__ROUTE__PURPOSE_CHOOSE_FOR_ME__", step: "purpose" },
    ACTION_PURPOSE_REFINE_CONFIRM: { route: "yes", step: "purpose", flags: ["confirm"] },
    ACTION_PURPOSE_REFINE_ADJUST: { route: "__ROUTE__PURPOSE_REFINE__", step: "purpose" },
    ACTION_PURPOSE_CONFIRM_SINGLE: { route: "yes", step: "purpose", flags: ["confirm"] },
    ACTION_PURPOSE_ESCAPE_CONTINUE: { route: "__ROUTE__PURPOSE_CONTINUE__", step: "purpose" },
    ACTION_PURPOSE_ESCAPE_FINISH_LATER: { route: "__ROUTE__PURPOSE_FINISH_LATER__", step: "purpose" },

    // Big Why
    ACTION_BIGWHY_INTRO_GIVE_EXAMPLE: { route: "__ROUTE__BIGWHY_GIVE_EXAMPLE__", step: "bigwhy" },
    ACTION_BIGWHY_INTRO_EXPLAIN_IMPORTANCE: { route: "__ROUTE__BIGWHY_EXPLAIN_IMPORTANCE__", step: "bigwhy" },
    ACTION_BIGWHY_EXPLAIN_ASK_3_QUESTIONS: { route: "__ROUTE__BIGWHY_ASK_3_QUESTIONS__", step: "bigwhy" },
    ACTION_BIGWHY_EXPLAIN_GIVE_EXAMPLE: { route: "__ROUTE__BIGWHY_GIVE_EXAMPLE__", step: "bigwhy" },
    ACTION_BIGWHY_REFINE_CONFIRM: { route: "yes", step: "bigwhy", flags: ["confirm"] },
    ACTION_BIGWHY_REFINE_ADJUST: { route: "__ROUTE__BIGWHY_REFINE__", step: "bigwhy" },
    ACTION_BIGWHY_ESCAPE_CONTINUE: { route: "__ROUTE__BIGWHY_CONTINUE__", step: "bigwhy" },
    ACTION_BIGWHY_ESCAPE_FINISH_LATER: { route: "__ROUTE__BIGWHY_FINISH_LATER__", step: "bigwhy" },

    // Role
    ACTION_ROLE_INTRO_GIVE_EXAMPLES: { route: "__ROUTE__ROLE_GIVE_EXAMPLES__", step: "role" },
    ACTION_ROLE_INTRO_EXPLAIN_MORE: { route: "__ROUTE__ROLE_EXPLAIN_MORE__", step: "role" },
    ACTION_ROLE_ASK_GIVE_EXAMPLES: { route: "__ROUTE__ROLE_GIVE_EXAMPLES__", step: "role" },
    ACTION_ROLE_REFINE_CONFIRM: { route: "yes", step: "role", flags: ["confirm"] },
    ACTION_ROLE_REFINE_ADJUST: { route: "__ROUTE__ROLE_ADJUST__", step: "role" },
    ACTION_ROLE_ESCAPE_CONTINUE: { route: "__ROUTE__ROLE_CONTINUE__", step: "role" },
    ACTION_ROLE_ESCAPE_FINISH_LATER: { route: "__ROUTE__ROLE_FINISH_LATER__", step: "role" },
    ACTION_ROLE_EXAMPLES_CHOOSE_FOR_ME: { route: "__ROUTE__ROLE_CHOOSE_FOR_ME__", step: "role" },

    // Entity
    ACTION_ENTITY_INTRO_FORMULATE: { route: "__ROUTE__ENTITY_FORMULATE__", step: "entity" },
    ACTION_ENTITY_INTRO_EXPLAIN_MORE: { route: "__ROUTE__ENTITY_EXPLAIN_MORE__", step: "entity" },
    ACTION_ENTITY_EXAMPLE_CONFIRM: { route: "yes", step: "entity", flags: ["confirm"] },
    ACTION_ENTITY_EXAMPLE_REFINE: { route: "__ROUTE__ENTITY_REFINE__", step: "entity" },
    ACTION_ENTITY_FORMULATE_FOR_ME: { route: "__ROUTE__ENTITY_FORMULATE_FOR_ME__", step: "entity" },
    ACTION_ENTITY_ESCAPE_CONTINUE: { route: "__ROUTE__ENTITY_CONTINUE__", step: "entity" },
    ACTION_ENTITY_ESCAPE_FINISH_LATER: { route: "__ROUTE__ENTITY_FINISH_LATER__", step: "entity" },

    // Strategy
    ACTION_STRATEGY_INTRO_FORMULATE: { route: "__ROUTE__STRATEGY_FORMULATE__", step: "strategy", status: "legacy" },
    ACTION_STRATEGY_INTRO_EXPLAIN_MORE: { route: "__ROUTE__STRATEGY_EXPLAIN_MORE__", step: "strategy" },
    ACTION_STRATEGY_REFINE_EXPLAIN_MORE: { route: "__ROUTE__STRATEGY_EXPLAIN_MORE__", step: "strategy" },
    ACTION_STRATEGY_QUESTIONS_EXPLAIN_MORE: { route: "__ROUTE__STRATEGY_EXPLAIN_MORE__", step: "strategy" },
    ACTION_STRATEGY_ASK_3_QUESTIONS: { route: "__ROUTE__STRATEGY_ASK_3_QUESTIONS__", step: "strategy" },
    ACTION_STRATEGY_ASK_GIVE_EXAMPLES: { route: "__ROUTE__STRATEGY_GIVE_EXAMPLES__", step: "strategy" },
    ACTION_STRATEGY_ASK_WRITE: { route: "__ROUTE__STRATEGY_FORMULATE__", step: "strategy", status: "legacy" },
    ACTION_STRATEGY_CONSOLIDATE: { route: "__ROUTE__STRATEGY_CONSOLIDATE__", step: "strategy" },
    ACTION_STRATEGY_CONFIRM_SATISFIED: { route: "__ROUTE__STRATEGY_CONFIRM_SATISFIED__", step: "strategy" },
    ACTION_STRATEGY_FINAL_CONTINUE: { route: "__ROUTE__STRATEGY_FINAL_CONTINUE__", step: "strategy" },
    ACTION_STRATEGY_ESCAPE_CONTINUE: { route: "__ROUTE__STRATEGY_CONTINUE__", step: "strategy" },
    ACTION_STRATEGY_ESCAPE_FINISH_LATER: { route: "__ROUTE__STRATEGY_FINISH_LATER__", step: "strategy" },

    // Target Group
    ACTION_TARGETGROUP_INTRO_EXPLAIN_MORE: { route: "__ROUTE__TARGETGROUP_EXPLAIN_MORE__", step: "targetgroup" },
    ACTION_TARGETGROUP_INTRO_ASK_QUESTIONS: { route: "__ROUTE__TARGETGROUP_ASK_QUESTIONS__", step: "targetgroup" },
    ACTION_TARGETGROUP_EXPLAIN_ASK_QUESTIONS: { route: "__ROUTE__TARGETGROUP_ASK_QUESTIONS__", step: "targetgroup" },
    ACTION_TARGETGROUP_POSTREFINE_CONFIRM: { route: "yes", step: "targetgroup", flags: ["confirm"] },
    ACTION_TARGETGROUP_POSTREFINE_ASK_QUESTIONS: { route: "__ROUTE__TARGETGROUP_ASK_QUESTIONS__", step: "targetgroup" },

    // Products and Services
    ACTION_PRODUCTSSERVICES_CONFIRM: { route: "__ROUTE__PRODUCTSSERVICES_CONFIRM__", step: "productsservices", flags: ["confirm"] },

    // Rules of the Game
    ACTION_RULES_INTRO_WRITE: { route: "__ROUTE__RULES_WRITE__", step: "rulesofthegame", status: "legacy" },
    ACTION_RULES_INTRO_EXPLAIN_MORE: { route: "__ROUTE__RULES_EXPLAIN_MORE__", step: "rulesofthegame" },
    ACTION_RULES_INTRO_GIVE_EXAMPLE: { route: "__ROUTE__RULES_GIVE_EXAMPLE__", step: "rulesofthegame" },
    ACTION_RULES_ASK_WRITE: { route: "__ROUTE__RULES_WRITE__", step: "rulesofthegame", status: "legacy" },
    ACTION_RULES_ASK_EXPLAIN_MORE: { route: "__ROUTE__RULES_EXPLAIN_MORE__", step: "rulesofthegame" },
    ACTION_RULES_ASK_GIVE_EXAMPLE: { route: "__ROUTE__RULES_GIVE_EXAMPLE__", step: "rulesofthegame" },
    ACTION_RULES_CONFIRM_ALL: { route: "__ROUTE__RULES_CONFIRM_ALL__", step: "rulesofthegame" },
    ACTION_RULES_REFINE_CONFIRM: { route: "yes", step: "rulesofthegame", flags: ["confirm"] },
    ACTION_RULES_REFINE_ADJUST: { route: "__ROUTE__RULES_ADJUST__", step: "rulesofthegame" },
    ACTION_RULES_ESCAPE_CONTINUE: { route: "__ROUTE__RULES_CONTINUE__", step: "rulesofthegame" },
    ACTION_RULES_ESCAPE_FINISH_LATER: { route: "__ROUTE__RULES_FINISH_LATER__", step: "rulesofthegame" },

    // Presentation
    ACTION_PRESENTATION_CHANGE: { route: "__ROUTE__PRESENTATION_CHANGE__", step: "presentation", status: "legacy" },
    ACTION_PRESENTATION_MAKE: { route: "__ROUTE__PRESENTATION_MAKE__", step: "presentation" },
    ACTION_PRESENTATION_ESCAPE_CONTINUE: { route: "__ROUTE__PRESENTATION_CONTINUE__", step: "presentation" },
    ACTION_PRESENTATION_ESCAPE_FINISH_LATER: { route: "__ROUTE__PRESENTATION_FINISH_LATER__", step: "presentation" },

    // Generic/system
    ACTION_START: { route: "", step: "system", status: "system" },
    ACTION_TEXT_SUBMIT: { route: "", step: "system", status: "system" },
    ACTION_WORDING_PICK_USER: { route: "__WORDING_PICK_USER__", step: "system", status: "system" },
    ACTION_WORDING_PICK_SUGGESTION: { route: "__WORDING_PICK_SUGGESTION__", step: "system", status: "system" },
  },
  menus: {
    // Step 0
    STEP0_MENU_META_RETURN: ["ACTION_STEP0_META_RETURN"],
    STEP0_MENU_READY_START: ["ACTION_STEP0_READY_START"],

    // Dream
    DREAM_MENU_INTRO: [
      "ACTION_DREAM_INTRO_EXPLAIN_MORE",
      "ACTION_DREAM_INTRO_START_EXERCISE",
    ],
    DREAM_MENU_WHY: [
      "ACTION_DREAM_WHY_GIVE_SUGGESTIONS",
      "ACTION_DREAM_WHY_START_EXERCISE",
    ],
    DREAM_MENU_SUGGESTIONS: [
      "ACTION_DREAM_SUGGESTIONS_PICK_ONE",
      "ACTION_DREAM_SUGGESTIONS_START_EXERCISE",
    ],
    DREAM_MENU_REFINE: [
      "ACTION_DREAM_REFINE_CONFIRM",
      "ACTION_DREAM_REFINE_START_EXERCISE",
    ],
    DREAM_MENU_ESCAPE: [
      "ACTION_DREAM_ESCAPE_CONTINUE",
      "ACTION_DREAM_ESCAPE_FINISH_LATER",
    ],
    DREAM_EXPLAINER_MENU_REFINE: [
      "ACTION_DREAM_EXPLAINER_REFINE_CONFIRM",
      "ACTION_DREAM_EXPLAINER_REFINE_ADJUST",
    ],
    DREAM_EXPLAINER_MENU_ESCAPE: [
      "ACTION_DREAM_EXPLAINER_CONTINUE",
      "ACTION_DREAM_EXPLAINER_FINISH_LATER",
    ],
    DREAM_EXPLAINER_MENU_SWITCH_SELF: [
      "ACTION_DREAM_SWITCH_TO_SELF",
    ],

    // Purpose
    PURPOSE_MENU_INTRO: [
      "ACTION_PURPOSE_INTRO_EXPLAIN_MORE",
      "ACTION_PURPOSE_EXPLAIN_ASK_3_QUESTIONS",
    ],
    PURPOSE_MENU_EXPLAIN: [
      "ACTION_PURPOSE_EXPLAIN_ASK_3_QUESTIONS",
      "ACTION_PURPOSE_EXPLAIN_GIVE_EXAMPLES",
    ],
    PURPOSE_MENU_POST_ASK: [
      "ACTION_PURPOSE_INTRO_EXPLAIN_MORE",
      "ACTION_PURPOSE_EXPLAIN_GIVE_EXAMPLES",
    ],
    PURPOSE_MENU_EXAMPLES: [
      "ACTION_PURPOSE_EXAMPLES_ASK_3_QUESTIONS",
      "ACTION_PURPOSE_EXAMPLES_CHOOSE_FOR_ME",
    ],
    PURPOSE_MENU_AFTER_CHOOSE: [
      "ACTION_PURPOSE_EXAMPLES_ASK_3_QUESTIONS",
      "ACTION_PURPOSE_CONFIRM_SINGLE",
    ],
    PURPOSE_MENU_REFINE: [
      "ACTION_PURPOSE_REFINE_CONFIRM",
      "ACTION_PURPOSE_REFINE_ADJUST",
    ],
    PURPOSE_MENU_CONFIRM_SINGLE: ["ACTION_PURPOSE_CONFIRM_SINGLE"],
    PURPOSE_MENU_ESCAPE: [
      "ACTION_PURPOSE_ESCAPE_CONTINUE",
      "ACTION_PURPOSE_ESCAPE_FINISH_LATER",
    ],

    // Big Why
    BIGWHY_MENU_INTRO: [
      "ACTION_BIGWHY_INTRO_GIVE_EXAMPLE",
      "ACTION_BIGWHY_INTRO_EXPLAIN_IMPORTANCE",
    ],
    BIGWHY_MENU_FROM_EXPLAIN: [
      "ACTION_BIGWHY_EXPLAIN_ASK_3_QUESTIONS",
      "ACTION_BIGWHY_EXPLAIN_GIVE_EXAMPLE",
    ],
    BIGWHY_MENU_FROM_GIVE: [
      "ACTION_BIGWHY_EXPLAIN_ASK_3_QUESTIONS",
      "ACTION_BIGWHY_INTRO_EXPLAIN_IMPORTANCE",
    ],
    BIGWHY_MENU_REFINE: [
      "ACTION_BIGWHY_REFINE_CONFIRM",
      "ACTION_BIGWHY_REFINE_ADJUST",
    ],
    BIGWHY_MENU_CONFIRM_SINGLE: ["ACTION_BIGWHY_REFINE_CONFIRM"],
    BIGWHY_MENU_ESCAPE: [
      "ACTION_BIGWHY_ESCAPE_CONTINUE",
      "ACTION_BIGWHY_ESCAPE_FINISH_LATER",
    ],

    // Role
    ROLE_MENU_INTRO: [
      "ACTION_ROLE_INTRO_GIVE_EXAMPLES",
      "ACTION_ROLE_INTRO_EXPLAIN_MORE",
    ],
    ROLE_MENU_ASK: ["ACTION_ROLE_ASK_GIVE_EXAMPLES"],
    ROLE_MENU_REFINE: [
      "ACTION_ROLE_REFINE_CONFIRM",
      "ACTION_ROLE_REFINE_ADJUST",
    ],
    ROLE_MENU_CONFIRM_SINGLE: ["ACTION_ROLE_REFINE_CONFIRM"],
    ROLE_MENU_ESCAPE: [
      "ACTION_ROLE_ESCAPE_CONTINUE",
      "ACTION_ROLE_ESCAPE_FINISH_LATER",
    ],
    ROLE_MENU_EXAMPLES: ["ACTION_ROLE_EXAMPLES_CHOOSE_FOR_ME"],

    // Entity
    ENTITY_MENU_INTRO: [
      "ACTION_ENTITY_INTRO_FORMULATE",
      "ACTION_ENTITY_INTRO_EXPLAIN_MORE",
    ],
    ENTITY_MENU_EXAMPLE: [
      "ACTION_ENTITY_EXAMPLE_CONFIRM",
      "ACTION_ENTITY_EXAMPLE_REFINE",
    ],
    ENTITY_MENU_CONFIRM_SINGLE: ["ACTION_ENTITY_EXAMPLE_CONFIRM"],
    ENTITY_MENU_FORMULATE: ["ACTION_ENTITY_FORMULATE_FOR_ME"],
    ENTITY_MENU_ESCAPE: [
      "ACTION_ENTITY_ESCAPE_CONTINUE",
      "ACTION_ENTITY_ESCAPE_FINISH_LATER",
    ],

    // Strategy
    STRATEGY_MENU_INTRO: ["ACTION_STRATEGY_INTRO_EXPLAIN_MORE"],
    STRATEGY_MENU_ASK: [
      "ACTION_STRATEGY_ASK_3_QUESTIONS",
      "ACTION_STRATEGY_ASK_GIVE_EXAMPLES",
    ],
    STRATEGY_MENU_REFINE: ["ACTION_STRATEGY_REFINE_EXPLAIN_MORE"],
    STRATEGY_MENU_QUESTIONS: ["ACTION_STRATEGY_QUESTIONS_EXPLAIN_MORE"],
    STRATEGY_MENU_CONFIRM: [
      "ACTION_STRATEGY_REFINE_EXPLAIN_MORE",
      "ACTION_STRATEGY_CONSOLIDATE",
      "ACTION_STRATEGY_CONFIRM_SATISFIED",
    ],
    STRATEGY_MENU_FINAL_CONFIRM: ["ACTION_STRATEGY_FINAL_CONTINUE"],
    STRATEGY_MENU_ESCAPE: [
      "ACTION_STRATEGY_ESCAPE_CONTINUE",
      "ACTION_STRATEGY_ESCAPE_FINISH_LATER",
    ],

    // Target Group
    TARGETGROUP_MENU_INTRO: [
      "ACTION_TARGETGROUP_INTRO_EXPLAIN_MORE",
      "ACTION_TARGETGROUP_INTRO_ASK_QUESTIONS",
    ],
    TARGETGROUP_MENU_EXPLAIN_MORE: ["ACTION_TARGETGROUP_EXPLAIN_ASK_QUESTIONS"],
    TARGETGROUP_MENU_EXPLAIN_ONLY: ["ACTION_TARGETGROUP_INTRO_EXPLAIN_MORE"],
    TARGETGROUP_MENU_POSTREFINE: [
      "ACTION_TARGETGROUP_POSTREFINE_CONFIRM",
      "ACTION_TARGETGROUP_POSTREFINE_ASK_QUESTIONS",
    ],

    // Products and Services
    PRODUCTSSERVICES_MENU_CONFIRM: ["ACTION_PRODUCTSSERVICES_CONFIRM"],

    // Rules of the Game
    RULES_MENU_INTRO: [
      "ACTION_RULES_INTRO_EXPLAIN_MORE",
      "ACTION_RULES_INTRO_GIVE_EXAMPLE",
    ],
    RULES_MENU_ASK_EXPLAIN: [
      "ACTION_RULES_ASK_EXPLAIN_MORE",
      "ACTION_RULES_ASK_GIVE_EXAMPLE",
    ],
    RULES_MENU_GIVE_EXAMPLE_ONLY: ["ACTION_RULES_ASK_GIVE_EXAMPLE"],
    RULES_MENU_EXPLAIN_ONLY: ["ACTION_RULES_ASK_EXPLAIN_MORE"],
    RULES_MENU_REFINE: [
      "ACTION_RULES_REFINE_CONFIRM",
      "ACTION_RULES_REFINE_ADJUST",
    ],
    RULES_MENU_CONFIRM: [
      "ACTION_RULES_CONFIRM_ALL",
      "ACTION_RULES_ASK_EXPLAIN_MORE",
      "ACTION_RULES_ASK_GIVE_EXAMPLE",
    ],
    RULES_MENU_ESCAPE: [
      "ACTION_RULES_ESCAPE_CONTINUE",
      "ACTION_RULES_ESCAPE_FINISH_LATER",
    ],

    // Presentation
    PRESENTATION_MENU_ASK: ["ACTION_PRESENTATION_MAKE"],
    PRESENTATION_MENU_ESCAPE: [
      "ACTION_PRESENTATION_ESCAPE_CONTINUE",
      "ACTION_PRESENTATION_ESCAPE_FINISH_LATER",
    ],
  },
  ui_flags: {
    "__ROUTE__PURPOSE_ASK_3_QUESTIONS__": { showPurposeHint: true },
  },
};
